# Generated by Django 6.0.7 on 2026-07-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('hot', 'Hot Beverages'), ('cold', 'Cold Beverages'), ('juice', 'Fresh Juices'), ('snack', 'Snacks'), ('dessert', 'Desserts')], max_length=20),
        ),
    ]
